### ISSUE TITLE
TTL for cached items

### ISSUE THREAD

**Issue by razekteixeira** [superwf/vuex-cache#6]
It could be a great feature to have some kind of configuration for all cache actions.
We could pass to the cache.dispatch an options objeto which may have a ttl (seconds or something else) that will clear that cached item after some configurable time.
This would avoid the delete of all cached items.

I'll try to do it and then I'll make a pill request as soon as I can.

Thanks for the plug-in ;)

**Comment by VitorLuizC** [comment]
That would be nice!

I was thinking if our dispatch interceptor can conflict with other Vuex's plugins, but since we're using it though `cache` namespace we can change it's API without any problem.

We can use cache dispatch arguments with an object.

```js
store.cache.dispatch({
  type: 'employee/fetchAll',
  payload: {
    company: this.company,
  },
  timeout: 1000 * 60 * 5, // 5 minutes.
});
```

Or just include an options after dispatch's payload.

```js
store.cache.dispatch('employee/fetchAll', { company: this.company }, {
  timeout: 1000 * 60 * 5, // 5 minutes.
});
```

@superwf

**Comment by superwf** [comment]
add timeout feature, try it. :tada:
